@startuml
@startuml
skinparam {
    ObjectBorderThickness<<active>> 3
}
hide stereotype

object "<u>:ObjectA" as oa <<active>>
object "<u>:ObjectB" as ob
object "<u>:ObjectC" as oc

oa -- ob : > A1: sendConfig
ob -r- oc : > A2: initializeStuff
@enduml
@enduml